# Generated by Django 5.1.3 on 2024-12-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("opponent", models.CharField(max_length=100)),
                ("points", models.PositiveIntegerField()),
                ("assists", models.PositiveIntegerField()),
                ("rebounds", models.PositiveIntegerField()),
                ("steals", models.PositiveIntegerField()),
                ("blocks", models.PositiveIntegerField()),
                ("turnovers", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("media", models.FileField(upload_to="highlights/")),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="performances.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=9)),
                ("matches", models.ManyToManyField(to="performances.match")),
            ],
        ),
    ]
